# programs/solana-htlc/Cargo.toml
[package]
name = "solana-htlc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.28.0"

[patch.crates-io]
getrandom = { git = "https://github.com/solana-labs/getrandom-sbf.git", branch = "main" }
